version: '3'

services:
  glances:
    container_name: glances
    image: nicolargo/glances:latest-alpine
    networks:
      - homelab
    restart: always
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=-w"

  nginx:
    image: nginx:latest

networks:
  homelab:
    external: true
